name: Fullstack CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    name: Backend Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Backend Dependencies
        run: npm i

      - name: Run Backend Tests
        run: npm test

  frontend:
    name: Frontend Test & Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Frontend Dependencies
        run: npm i

      - name: Run Frontend Tests
        run: CI=true npm test -- --watchAll=false

      - name: Build Frontend
        run: npm run build
